using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using CognitivePlatform.Api.Conversation;
using CognitivePlatform.Api.Data;
using CognitivePlatform.Api.Domains.Journal.Interfaces;
using CognitivePlatform.Api.Insights.Models;
using CognitivePlatform.Api.Interpreter;
using Microsoft.Extensions.Logging;

namespace CognitivePlatform.Api.Insights;

/// <summary>
/// Phase D (ENH-31) insight provider. Scans recent journal entries (last 3 days) for
/// cognitive distortion language — catastrophising, all-or-nothing thinking, mind-reading,
/// or fortune-telling — and gently reflects the pattern back to the user.
///
/// <para>
/// Opt-in: disabled by default. Enable via EnableCognitiveDistortionDetector (NL) or
/// the key "cognitive_distortion_detector_enabled" in IObjectStore.
/// </para>
///
/// <para>
/// Trigger:          Feature flag enabled AND LLM detects distortion language in journals.
/// Message:          Gentle, non-clinical reflection generated by the LLM.
/// DeduplicationKey: cog.distortion
/// RepeatWindow:     24 hours (InsightPolicy default; no category override required).
/// InsightCategory:  Wellbeing
/// </para>
/// </summary>
public sealed class CognitiveDistortionInsightProvider : IInsightProvider
{
    internal const string FlagKey = "cognitive_distortion_detector_enabled";

    private static readonly JsonSerializerOptions JsonOptions =
        new() { PropertyNameCaseInsensitive = true };

    private readonly IJournalService                              _journalService;
    private readonly ILlmRouter                                   _router;
    private readonly IObjectStore                                  _objectStore;
    private readonly ILogger<CognitiveDistortionInsightProvider>  _logger;

    public InsightCategory Category => InsightCategory.Wellbeing;

    public CognitiveDistortionInsightProvider( IJournalService                             journalService
                                             , ILlmRouter                                  router
                                             , IObjectStore                                 objectStore
                                             , ILogger<CognitiveDistortionInsightProvider> logger )
    {
        _journalService = journalService ?? throw new ArgumentNullException(nameof(journalService));
        _router         = router         ?? throw new ArgumentNullException(nameof(router));
        _objectStore    = objectStore    ?? throw new ArgumentNullException(nameof(objectStore));
        _logger         = logger         ?? throw new ArgumentNullException(nameof(logger));
    }

    public async IAsyncEnumerable<Insight> GenerateAsync(
        ConversationContext                        context
      , [EnumeratorCancellation] CancellationToken cancellationToken = default )
    {
        cancellationToken.ThrowIfCancellationRequested();

        var settings = _objectStore.Get<CognitiveDistortionSettings>(FlagKey);

        if (settings?.IsEnabled != true)
            yield break;

        var threeDaysAgo = DateTimeOffset.UtcNow.AddDays(-3);
        var entries      = _journalService.ListEntries(fromUtc: threeDaysAgo);

        if (entries.Count == 0)
            yield break;

        var prompt   = BuildPrompt(entries);
        var response = (await _router.SendAsync(prompt
                                              , context
                                              , complexity: TaskComplexity.Standard
                                              , ct:         cancellationToken)).Content;

        var result = TryParseResponse(response);

        if (result?.Detected != true || string.IsNullOrWhiteSpace(result.Message))
            yield break;

        yield return new Insight
                     {
                             Message          = result.Message
                           , DeduplicationKey = "cog.distortion"
                           , Category         = InsightCategory.Wellbeing
                           , Priority         = InsightPriority.Normal
                           , Reasoning        = new InsightReasoning
                                               {
                                                       Explanation = string.IsNullOrWhiteSpace(result.Pattern)
                                                                         ? "Cognitive distortion language detected in recent journals."
                                                                         : $"Pattern detected: {result.Pattern}."
                                               }
                     };
    }

    private static string BuildPrompt(IReadOnlyList<CognitivePlatform.Api.Models.JournalEntryWithRevision> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine("You are a gentle journaling companion. Read these recent journal excerpts and determine if there is notable cognitive distortion language present.");
        sb.AppendLine();
        sb.AppendLine("Recent journal excerpts:");

        foreach (var entry in entries.Take(5))
        {
            var text = entry.LatestRevision.Text;
            if (text.Length > 300) text = string.Concat(text.AsSpan(0, 300), "…");
            sb.AppendLine($"  [{entry.Entry.CreatedUtc:yyyy-MM-dd}] {text}");
        }

        sb.AppendLine();
        sb.AppendLine("""
            Cognitive distortion patterns to look for:
            - Catastrophising ("everything is ruined", "this is a disaster")
            - All-or-nothing ("I always fail", "I never get it right")
            - Mind-reading ("they think I'm", "everyone believes")
            - Fortune-telling ("this will never work", "I know it will go wrong")

            Respond with STRICT JSON only — no prose, no markdown fences, no commentary:
            {
              "detected": true | false,
              "pattern":  "catastrophising" | "all-or-nothing" | "mind-reading" | "fortune-telling" | "",
              "message":  "<a gentle, non-judgmental, non-clinical 1–2 sentence reflection>"
            }

            Rules:
            - detected should be true only when the pattern is clear and unambiguous
            - message must be curious, never diagnostic — e.g. "I noticed some pretty absolute language..."
            - never use clinical terminology
            - if no clear pattern: {"detected":false,"pattern":"","message":""}
            """);

        return sb.ToString();
    }

    private DistortionResult? TryParseResponse(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return null;

        var json = ExtractJsonObject(raw);
        if (json is null)
        {
            _logger.LogDebug("CognitiveDistortionInsightProvider: no JSON in response. Raw={Raw}", raw);
            return null;
        }

        try
        {
            return JsonSerializer.Deserialize<DistortionResult>(json, JsonOptions);
        }
        catch (JsonException ex)
        {
            _logger.LogDebug(ex, "CognitiveDistortionInsightProvider: malformed JSON. Raw={Raw}", raw);
            return null;
        }
    }

    private static string? ExtractJsonObject(string raw)
    {
        var start = raw.IndexOf('{');
        if (start < 0) return null;

        var depth = 0;
        for (var i = start; i < raw.Length; i++)
        {
            switch (raw[i])
            {
                case '{': depth++; break;
                case '}':
                    depth--;
                    if (depth == 0) return raw.Substring(start, i - start + 1);
                    break;
            }
        }

        return null;
    }

    private sealed class DistortionResult
    {
        public bool    Detected { get; set; }
        public string? Pattern  { get; set; }
        public string? Message  { get; set; }
    }
}
